### ISSUE TITLE
Xcode 9 support state

### ISSUE THREAD

**Issue by NickAb** [facebook/FBSimulatorControl#435] opened 2017-08-17 14:22 UTC
I wanted to check migration path to Xcode 9.
I am using Xcode 9 beta 5.

If I use stable fbsimctl 0.4.0 build installed via `brew install fbsimctl`(using Xcode 8.3.2) then `fbsimctl list` command will result in
```
Error Domain=com.facebook.FBControlCore Code=0 "Attempting to load a file at path '/Applications/Xcode-9.beta.5.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework', but it does not exist" UserInfo={NSLocalizedDescription=Attempting to load a file at path '/Applications/Xcode-9.beta.5.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework', but it does not exist}
```

Trying to install latest fbsimctl via `brew install fbsimctl --HEAD` fails with 
```
The following build commands failed:
	CompileC build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/XCTestBootstrap.build/Objects-normal/x86_64/FBXCTestDestination.o XCTestBootstrap/Configuration/FBXCTestDestination.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

What is current status on Xcode 9 and iOS 11 support?

**Comment by NickAb** [comment] 2017-08-17 15:01
Current solution I found is to build `fbsimctl` with `Xcode 8.3.3` from commit `4a3a339ca325ae2ac0b34fef92605204b79e0c09`.
After that you can `xcode-select Xcode-9.beta.5` and use fbsimctl to launch iOS 11 simulators, etc.

**Comment by MoOx** [comment] 2017-09-14 15:41
Meanwhile Xcode 9 is supported...

```console
git clone https://github.com/facebook/FBSimulatorControl.git
cd FBSimulatorControl
git checkout 4a3a339ca325ae2ac0b34fef92605204b79e0c09
sudo xcode-select -s /Applications/Xcode-8.app
./build.sh fbsimctl build output
```

Bins will be in output/bin, just add this full path to your PATH and you are good to go until Xcode 9 is supported.

**Comment by vincentkjj** [comment] 2017-09-14 18:38
Hi @MoOx 

Your method does not seem to work for me. I am seeing the following error still after following your steps. It's trying to locate the CoreSimulator framework in Xcode 9 which does not exist. I did use git clone and checked out the same commit as you mentioned. What could be wrong here?

`Error Domain=com.facebook.FBControlCore Code=0 "Attempting to load a file at path '/Applications/Xcode-9.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework', but it does not exist" UserInfo={NSLocalizedDescription=Attempting to load a file at path '/Applications/Xcode-9.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework', but it does not exist}`

**Comment by MoOx** [comment] 2017-09-14 19:31
I can see in your notes that the version of Xcode is `Xcode-9`. My instructions are for Xcode 8. I just built it on my machine this way a few our ago (my machine is a macbook pro 2016 that run macOS 10.13 with Xcode 8+ and 9-beta.6.

**Comment by vincentkjj** [comment] 2017-09-14 21:20
ah I see I misread your comment. thanks!

**Comment by heuism** [comment] 2017-09-19 01:31
Hi guys, so is this issue resolved? Cause I am running into the same issue. And it seems like there is no current way for Xcode 9 GM. Or can I have both Xcode 9 GM and Xcode 8 at the same time? Thanks

**Comment by MoOx** [comment] 2017-09-19 04:09
Just name Xcode 8 "Xcode-8.app" and you won't have any problem :)
https://github.com/facebook/FBSimulatorControl/issues/435#issuecomment-329522823 works for me this way.

**Comment by foxalice92** [comment] 2017-09-27 05:54
Hello guys! This error still reproduced for me after updating Xcode to Version 9.0 (9A235), Please, help me.
'Failed to private frameworks for FBSimulatorControl with error Error Domain=com.facebook.FBControlCore Code=0 "Attempting to load a file at path '/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework', but it does not exist"

**Comment by vigneshprabhu20** [comment] 2017-12-15 11:43
I am also getting the same Error! with Xcode Version 9.2 (9C40b), Mac version: 10.13.2 (17C88)

** BUILD FAILED **


The following build commands failed:
	CompileC build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/XCTestBootstrap.build/Objects-normal/x86_64/FBTestManagerTestReporterTestCase.o XCTestBootstrap/TestManager/FBTestManagerTestReporterTestCase.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by MoOx** [comment] 2018-01-10 08:06
It just worked for me with Xcode 9.2.

**Comment by yongpingchen** [comment] 2018-02-20 07:25
I had different error with Xcode 9.2

```
The following build commands failed:
	CompileSwift normal x86_64 /Users/yongping/Documents/CompanyProjects/ReactNative/FBSimulatorControl/fbsimctl/FBSimulatorControlKit/Sources/SimulatorReporter.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by edcs** [comment] 2018-02-20 11:35
Having the same problem as @yongpingchen here.

**Closed** 2018-05-20 12:06 UTC
